FROM registry.access.redhat.com/rhscl/mongodb-36-rhel7:latest

MAINTAINER Victor Ameh <victor.ameh@aot-technologies.com>

LABEL Remarks="Dockerfile to update packages to address vulnerability CVE-2021-43527"

#Update Software Repository

RUN yum -y update
