FROM artifacts.developer.gov.bc.ca/bcgov-docker-local/mongodb-36-ha:latest

MAINTAINER Victor Ameh <victor.ameh@aot-technologies.com>

LABEL Remarks="Dockerfile to update packages to address vulnerability CVE-2021-43527"

#Update Software Repository
USER root

# RUN yum -y update

USER default
